services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py create_superuser &&
             python manage.py create_trust_pages &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 3 --bind unix:/home/app/web/app.sock site_service.wsgi:application"
    environment:
      - DJANGO_SETTINGS_MODULE=site_service.settings
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/entrypoint.sh:/var/www/certbot/entrypoint.sh
#    env_file:
#      - .env
#    entrypoint: ["/bin/sh", "-c", "chmod +x /var/www/certbot/entrypoint.sh && /var/www/certbot/entrypoint.sh"]

volumes:
  postgres_data:
  static_volume:
  media_volume:
