# Generated by Django 5.1.5 on 2025-02-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteoptions",
            options={"verbose_name": "Options", "verbose_name_plural": "Options"},
        ),
    ]
