# Generated by Django 5.1.5 on 2025-02-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_siteoptions_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteoptions",
            name="hide_sponsor_url",
            field=models.BooleanField(default=False),
        ),
    ]
