# Generated by Django 5.1.5 on 2025-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_siteoptions_hide_sponsor_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteoptions",
            name="ai_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
