# Generated by Django 5.1.5 on 2025-02-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteoptions_ai_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteoptions",
            name="ai_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="siteoptions",
            name="hide_sponsor_url",
            field=models.BooleanField(
                default=False, help_text="Hide sponsor url from search engines"
            ),
        ),
    ]
