# Generated by Django 5.1.5 on 2025-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_siteoptions_ai_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteoptions",
            name="site_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="siteoptions",
            name="ai_model",
            field=models.CharField(
                blank=True,
                help_text="Model used for text generation. For example: meta-llama/Llama-3.3-70B-Instruct-Turbo",
                max_length=255,
                null=True,
            ),
        ),
    ]
