# Generated by Django 5.1.5 on 2025-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_partners"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteoptions",
            name="custom_css",
            field=models.TextField(blank=True, null=True),
        ),
    ]
