# Generated by Django 5.1.5 on 2025-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_siteoptions_custom_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteoptions",
            name="sponsor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="siteoptions",
            name="sponsor_url",
            field=models.URLField(
                blank=True,
                help_text="Referral link to sponsor",
                max_length=255,
                null=True,
            ),
        ),
    ]
