# Generated by Django 5.1.5 on 2025-02-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_siteoptions_sponsor_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteoptions",
            old_name="ai_model",
            new_name="ai_chat_model",
        ),
        migrations.AddField(
            model_name="siteoptions",
            name="ai_image_model",
            field=models.CharField(
                blank=True,
                help_text="Model used for image generation. For example: black-forest-labs/FLUX.1.1-pro",
                max_length=255,
                null=True,
            ),
        ),
    ]
