# Generated by Django 5.1.5 on 2025-02-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_ai_model_siteoptions_ai_chat_model_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteoptions",
            old_name="sponsor_name",
            new_name="brand_name",
        ),
        migrations.AlterField(
            model_name="siteoptions",
            name="ai_image_model",
            field=models.CharField(
                blank=True,
                help_text="Model used for image generation. For example: black-forest-labs/FLUX.1-pro",
                max_length=255,
                null=True,
            ),
        ),
    ]
