# Generated by Django 5.1.5 on 2025-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_sponsor_name_siteoptions_brand_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteoptions",
            old_name="site_type",
            new_name="activity",
        ),
        migrations.AlterField(
            model_name="siteoptions",
            name="ai_chat_model",
            field=models.CharField(
                blank=True,
                help_text="Model used for text generation. For example: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
                max_length=255,
                null=True,
            ),
        ),
    ]
