# Generated by Django 5.1.5 on 2025-03-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_site_type_siteoptions_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteoptions",
            name="ai_chat_model",
            field=models.CharField(
                blank=True,
                help_text="Model used for text generation. For example: <b>meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo</b>, <b>mistralai/Mistral-7B-Instruct-v0.3</b>",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="siteoptions",
            name="ai_image_model",
            field=models.CharField(
                blank=True,
                help_text="Model used for image generation. For example: <b>black-forest-labs/FLUX.1-pro</b>",
                max_length=255,
                null=True,
            ),
        ),
    ]
