# Generated by Django 5.1.5 on 2025-02-03 09:07

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="title",
        ),
        migrations.CreateModel(
            name="SEOTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="seo.seo",
                    ),
                ),
            ],
            options={
                "verbose_name": "seo Translation",
                "db_table": "seo_seo_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
