"""
Django settings for site_service project.

Generated by "django-admin startproject" using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@=@bleu_xok@@#ow5cmzrq4nie(7toadnv$o&ctp)d*+cn%6&!"

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",

    "imagekit",
    "django_ckeditor_5",
    "meta",
    "rosetta",
    "parler",
    "easy_thumbnails",
    "filer",
    "bootstrap5",
    "sass_processor",
    "compressor",
    "django_browser_reload",
    "mptt",

    "core",
    "pages",
    "seo",
    "menu",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "site_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.all_pages",
                "core.context_processors.current_url_name",
                "core.context_processors.language_flag_map",
            ],
        },
    },
]

WSGI_APPLICATION = "site_service.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
]
LANGUAGE_FLAG_MAP = {
    "en": "gb",
    "fr": "fr",
}

LOCALE_PATHS = [
    BASE_DIR / "locale",
]
PARLER_LANGUAGES = {
    1: (
        {"code": "en"},
        {"code": "fr"},
    ),
    "default": {
        "fallback": "en",
        "hide_untranslated": False,
    }
}

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [
    BASE_DIR / "templates/static",
    BASE_DIR / "node_modules",
]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "sass_processor.finders.CssFinder",
]

SASS_PROCESSOR_ROOT = BASE_DIR / "templates/static"
SASS_PROCESSOR_INCLUDE_DIRS = [
    BASE_DIR / "node_modules",
]
SASS_PROCESSOR_ENABLED = True
SASS_PROCESSOR_AUTO_INCLUDE = False

# Media
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

FILER_STORAGES = {
    "public": {
        "main": {
            "ENGINE": "filer.storage.PublicFileSystemStorage",
            "OPTIONS": {
                "location": os.path.join(MEDIA_ROOT, "filer"),
                "base_url": "/media/filer/",
            },
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CKEditor config
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": ["heading", "|", "bold", "italic", "link",
            "bulletedList", "numberedList", "blockQuote", "imageUpload", ],

    },
    "extends": {
        "blockToolbar": [
            "paragraph", "heading1", "heading2", "heading3",
            "|",
            "bulletedList", "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": ["heading", "|", "outdent", "indent", "|", "bold", "italic",
            "link", "underline", "strikethrough",
            "code", "subscript", "superscript", "highlight", "|", "codeBlock",
            "sourceEditing", "insertImage",
            "bulletedList", "numberedList", "todoList", "|", "blockQuote",
            "|", "fontSize", "fontFamily", "fontColor", "fontBackgroundColor",
            "mediaEmbed", "removeFormat",
            "insertTable", ],
        "image": {
            "toolbar": ["imageTextAlternative", "|", "imageStyle:alignLeft",
                "imageStyle:alignRight", "imageStyle:alignCenter",
                "imageStyle:side", "|"],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ]

        },
        "table": {
            "contentToolbar": ["tableColumn", "tableRow", "mergeTableCells",
                "tableProperties", "tableCellProperties"],
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph", "title": "Paragraph",
                    "class": "ck-heading_paragraph"
                },
                {
                    "model": "heading1", "view": "h1", "title": "Heading 1",
                    "class": "ck-heading_heading1"
                },
                {
                    "model": "heading2", "view": "h2", "title": "Heading 2",
                    "class": "ck-heading_heading2"
                },
                {
                    "model": "heading3", "view": "h3", "title": "Heading 3",
                    "class": "ck-heading_heading3"
                }
            ]
        }
    },
    "list": {
        "properties": {
            "styles": "true",
            "startIndex": "true",
            "reversed": "true",
        }
    }
}

CKEDITOR_5_UPLOAD_PATH = "media/"

# Make sure CKEDITOR_5_UPLOAD_PATH is inside MEDIA_ROOT
CKEDITOR_5_MEDIA_PREFIX = f"{MEDIA_URL}{CKEDITOR_5_UPLOAD_PATH}"
