# Generated by Django 5.1.5 on 2025-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_page_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="ai_additional_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="page",
            name="auto_generate_content",
            field=models.BooleanField(default=False),
        ),
    ]
