# Generated by Django 5.1.5 on 2025-02-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_options_page_created_page_publish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
