# Generated by Django 5.1.5 on 2025-02-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_page_ai_additional_info_page_auto_generate_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="ai_additional_info",
            field=models.TextField(
                blank=True,
                help_text="In addition to the main request, these additional instructions will be used (they are in priority)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="auto_generate_content",
            field=models.BooleanField(
                default=False,
                help_text="If active, new content will be generated on save, but only if the content is empty",
            ),
        ),
    ]
