# Generated by Django 5.1.5 on 2025-02-02 14:00

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_page_slug_alter_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="images/"
            ),
        ),
    ]
