# Generated by Django 5.1.5 on 2025-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_page_ai_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="ai_additional_info",
            field=models.TextField(
                blank=True, help_text="Additional AI generation instructions", null=True
            ),
        ),
    ]
