# Generated by Django 5.1.5 on 2025-02-03 11:37

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_remove_page_content_remove_page_slug_and_more"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_image",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
