# Generated by Django 5.1.5 on 2025-02-03 15:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_page_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagetranslation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
    ]
