# Generated by Django 5.1.5 on 2025-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_pagetranslation_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagetranslation",
            name="slug",
        ),
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(default="qq", max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
