# Generated by Django 5.1.5 on 2025-02-05 21:42

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=255)),
                ("sponsor_url", models.URLField(max_length=255)),
                (
                    "sponsor_logo",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsor_logo",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
        ),
    ]
