# Generated by Django 5.1.5 on 2025-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="game",
            name="order",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
