# Generated by Django 5.1.5 on 2025-02-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_options_game_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-order"]},
        ),
    ]
