# Generated by Django 5.1.5 on 2025-02-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="named_url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Choose URL"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Custom URL"
            ),
        ),
    ]
