# Generated by Django 5.1.5 on 2025-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menuitem_named_url_alter_menuitem_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="named_url",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(default="qwe", max_length=200),
            preserve_default=False,
        ),
    ]
