# Generated by Django 5.1.5 on 2025-03-02 23:19

import django.db.models.deletion
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_remove_menuitem_named_url_alter_menuitem_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                default=menu.models.get_default_menu,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menu.menu",
            ),
        ),
    ]
