# Generated by Django 5.1.5 on 2025-02-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0002_remove_seo_description_remove_seo_keywords_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seotranslation",
            name="keywords",
        ),
    ]
