# Generated by Django 5.1.5 on 2025-02-22 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("seo", "0003_remove_seotranslation_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seo",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seo_pages",
                to="contenttypes.contenttype",
            ),
        ),
    ]
